### ISSUE TITLE
Jobs and Ranks have spells

### ISSUE THREAD

**Issue by JohannesNeo** [Ayditor/HPW_Rewrite#19]
Hey, its no issue but it's either a question.
I want to make that if you are as an example 'Lord Voldemort' then you only have Avada kedavra and if you change job to Perfect etc then you don't have Avada kedavra anymore.

And If you are VIP then you have Avis or Purple Firecrackers etc and If you are not VIP then you don't have it.

**Comment by JohannesNeo** [comment]
nvm the shitty devs doesn't care about their downloaders

**Comment by Ayditor** [comment]
@JohannesNeo 
1) sorry for slow response, I rarely visit github and mail inbox
2) I cant help you right now due to my university exams
3) actually you can restrict spawning books for your jobs; it was just an idea that everyone can use any spell if he had learned it but not everyone can get that spellbook.
